// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using GameTextArchive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace GameTextArchive.Core.Migrations
{
    [DbContext(typeof(GameTextDbContext))]
    partial class GameTextDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameTextArchive.Lexeme", b =>
                {
                    b.Property<Guid>("lexemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("lexemeId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Lexemes");
                });

            modelBuilder.Entity("GameTextArchive.TextRecord", b =>
                {
                    b.Property<Guid>("recordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EditorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, JsonElement>>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Text" });

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpeakerId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("recordId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("TextRecords");
                });

            modelBuilder.Entity("GameTextArchive.TextRecordLexeme", b =>
                {
                    b.Property<Guid>("recordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("lexemeId")
                        .HasColumnType("uuid");

                    b.Property<int>("frequency")
                        .HasColumnType("integer");

                    b.HasKey("recordId", "lexemeId");

                    b.HasIndex("lexemeId");

                    b.ToTable("TextRecordLexemes");
                });

            modelBuilder.Entity("GameTextArchive.TextRecordLexeme", b =>
                {
                    b.HasOne("GameTextArchive.Lexeme", "lexeme")
                        .WithMany()
                        .HasForeignKey("lexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTextArchive.TextRecord", "record")
                        .WithMany()
                        .HasForeignKey("recordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lexeme");

                    b.Navigation("record");
                });
#pragma warning restore 612, 618
        }
    }
}
